import { NextRequest, NextResponse } from "next/server";
import { readFile, stat } from "fs/promises";

/**
 * Serves TTS audio files generated by the OpenClaw gateway.
 * The gateway writes audio to temp files on disk; this route reads and streams them.
 *
 * GET /api/openclaw/tts-audio?path=/tmp/tts-xxx/voice-123.mp3
 */
export async function GET(request: NextRequest) {
  const audioPath = request.nextUrl.searchParams.get("path");

  if (!audioPath) {
    return NextResponse.json({ error: "Missing path parameter" }, { status: 400 });
  }

  // Security: only allow reading from temp directories
  const allowed = audioPath.startsWith("/tmp/") || audioPath.startsWith("/var/folders/");
  if (!allowed) {
    return NextResponse.json({ error: "Path not allowed" }, { status: 403 });
  }

  // Security: only allow audio file extensions
  if (!audioPath.match(/\.(mp3|wav|ogg|opus|webm|m4a)$/i)) {
    return NextResponse.json({ error: "Not an audio file" }, { status: 403 });
  }

  try {
    const fileStat = await stat(audioPath);
    if (!fileStat.isFile()) {
      return NextResponse.json({ error: "Not a file" }, { status: 404 });
    }

    const buffer = await readFile(audioPath);
    const ext = audioPath.split(".").pop()?.toLowerCase() ?? "mp3";
    const mimeTypes: Record<string, string> = {
      mp3: "audio/mpeg",
      wav: "audio/wav",
      ogg: "audio/ogg",
      opus: "audio/opus",
      webm: "audio/webm",
      m4a: "audio/mp4",
    };

    return new NextResponse(buffer, {
      headers: {
        "Content-Type": mimeTypes[ext] ?? "audio/mpeg",
        "Content-Length": String(buffer.length),
        "Cache-Control": "no-store",
      },
    });
  } catch {
    return NextResponse.json({ error: "File not found" }, { status: 404 });
  }
}
